GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/Lupio

###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "id": "",
    "email" : "test",
    "firstName": "test",
    "lastName": "test"
}

###

PUT http://localhost:3000/api/users/912
Content-Type: application/json

{
    "email" : "test",
    "firstName": "test",
    "lastName": "test"
}

###

DELETE http://localhost:3000/api/users/912


