GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users/add
Content-Type: application/json

{
    "id": "",
    "userName" : "hej",
    "firstName": "hoho",
    "lastName": "hihi"
}

###
GET http://localhost:3000/api/users/566589

###

PUT http://localhost:3000/api/users/update/55674

###

DELETE http://localhost:3000/api/users/delete/55666

###

