GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/Lupio

###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "id": "",
    "email" : "test",
    "firstName": "test",
    "lastName": "test"
}

###

PUT http://localhost:3000/api/users/82b97c3a-4ef0-408e-bc41-983beb56aaa0
Content-Type: application/json

{
    "email" : "test",
    "firstName": "test",
    "lastName": "test"
}

###

DELETE http://localhost:3000/api/users/82b97c3a-4ef0-408e-bc41-983beb56aaa0


